// Frontend/src/home_components/InputSquealComponents/LinkInserter.jsx
import React from 'react';

const LinkInserter = ({ handleInsertLink, selection }) => {
  const handleButtonClick = () => {
    const url = prompt("Inserisci l'URL del link:");
    handleInsertLink(url);
  };

  return (
    <div>
      <button onClick={handleButtonClick}>Inserisci Link</button>
    </div>
  );
};

export default LinkInserter;

// SMMApp/squealer-smm/src/components/InputSquealComponents/LinkInserter.vue
<template>
  <button
    class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
    @click="promptForLink"
  >
    Inserisci Link
  </button>
</template>

<script>
export default {
  methods: {
    promptForLink() {
      const url = prompt("Inserisci l'URL del link:");
      if (url) {
        this.$emit("insertLink", url);
      }
    },
  },
};
</script>
