// Frontend/src/home_components/InputSquealComponents/MessageInput.jsx
import React from "react";
import { Form } from "react-bootstrap";

const MessageInput = ({ message, handleMessageChange, handleTextSelect }) => {
	return (
		<Form.Control
			as="textarea"
			value={message}
			onChange={handleMessageChange}
			onSelect={handleTextSelect}
			placeholder="Inserisci il tuo messaggio..."
			style={{ height: "100px", marginBottom: "10px" }}
		/>
	);
};

export default MessageInput;

// SMMApp/squealer-smm/src/components/InputSquealComponents/MessageInput.vue
<template>
  <textarea
    class="form-textarea w-full p-2 border rounded"
    :value="message"
    @input="$emit('messageChange', $event.target.value)"
    @select="$emit('textSelect', $event)"
    placeholder="Inserisci il tuo messaggio..."
  ></textarea>
</template>

<script>
export default {
  props: {
    message: String,
  },
};
</script>
